openapi: 3.0.0
info:
  title: SiteIQ SEO Reports API
  description: API for generating, retrieving, scoring, and managing SEO reports.
  version: 1.0.0

servers:
  - url: http://localhost:5000/api/

tags:
  - name: SEO Reports
    description: All endpoints related to SEO report generation and management

paths:
  /api/seoreports/generate:
    post:
      summary: Generate and score a new SEO report
      tags: [SEO Reports]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - phrase
                - domain
              properties:
                phrase:
                  type: string
                  example: "buy shoes online"
                domain:
                  type: string
                  example: "example.com"
      responses:
        '200':
          description: Report created or updated successfully
        '400':
          description: Missing required fields
        '500':
          description: Internal server error

  /api/seoreports/delete/{jid}:
    delete:
      summary: Delete a phrase result or entire report by jid
      tags: [SEO Reports]
      parameters:
        - in: path
          name: jid
          required: true
          schema:
            type: string
          description: Job ID of the phrase/report to delete
      responses:
        '200':
          description: Phrase or report deleted
        '400':
          description: Missing jid
        '404':
          description: Report or phrase not found
        '500':
          description: Internal server error

  /api/seoreports/return/{jid}:
    get:
      summary: Return the saved SEO report data for a given jid
      tags: [SEO Reports]
      parameters:
        - in: path
          name: jid
          required: true
          schema:
            type: string
          description: Job ID for the report
      responses:
        '200':
          description: Report found and returned
        '400':
          description: Missing jid parameter
        '404':
          description: Report not found
        '500':
          description: Internal server error
